### ISSUE TITLE
MP3

### ISSUE THREAD

**Issue by SharkPolo** [arblast/Chrome-Audio-Capturer#1]
Any plan to add the possibility to save as .mp3?

**Comment by arblast** [comment]
working on it!

**Comment by SharkPolo** [comment]
Perfect!
Thank you so much and your extension is the best one!
Keep the good work.

**Comment by arblast** [comment]
Extension has been updated :)
Do let me know if there are any bugs or features you want added, and thanks for the feedback!

**Comment by SharkPolo** [comment]
Amazing! Thank you so much! :)
