### ISSUE TITLE
Theoretical stuffs

### ISSUE THREAD

**Issue by legostax** [arblast/Chrome-Audio-Capturer#3]
Is it only the Chrome Web Store that doesn't allow extensions for record audio from places like YouTube?

If so, does that mean that Chrome fully allows a Javascript call to record audio from places like YouTube?

Not that I would download and modify your extension for my personal use or anything. ;)

**Comment by arblast** [comment]
Yes to both questions. The web store ToS doesn't allow any extensions that "enables the unauthorized download of streaming content or media" so I had to add a few lines of extra code to disable that. With that said, I might just re-enable capture on YouTube until they decide to contact me directly in the next update... But if you want to, feel free to modify the extension for personal use as long as you don't publish it :)

**Comment by legostax** [comment]
Thanks for the speedy response!
Interesting...one would think that Google would add restrictions like that in Chrome (not Chromium) as well...
