### ISSUE TITLE
Change hotkeys

### ISSUE THREAD

**Issue by cyrillkuettel** [arblast/Chrome-Audio-Capturer#36]
A nice features would be changing the hotkeys. Are you interested in implementing this or a pull request?

**Comment by edshen17** [comment]
I was able to change them by going to chrome://extensions/shortcuts -> Keyboard shortcuts -> Chrome Audio Capture. There you can change start/stop capturing.

**Comment by cyrillkuettel** [comment]
That's a nice easy fix. I think we can close this then
