### ISSUE TITLE
Can the maximum capture time be extended to 30 minutes?

### ISSUE THREAD

**Issue by monk1900** [arblast/Chrome-Audio-Capturer#8]
I tried to manually edit the code but it seems I am missing to edit the numbers somewhere, as the timer continues to be 20 mins.

**Comment by arblast** [comment]
you can actually do this in the settings in the extension, just check the box that says remove capture time limit.

**Comment by monk1900** [comment]
I know that I can remove the capture limit, but I want the recording to stop automatically after 25 minutes for example.

**Comment by Overlife89** [comment]
I'm interested in the same thing, to set the time that automatically stops for over 20 minutes. 1 hour, 2 hours, how long I have set the automatic stop.
